{"uuid": "78af8d86-a992-4f59-961f-9866428f7079", "children": ["935e88b6-eea5-4c43-bddb-510548347c9d"], "befores": [{"name": "setup", "status": "failed", "statusDetails": {"message": "AssertionError: User icon is not presented\n", "trace": "  File \"/Users/larisayusina/Desktop/environments/selenium_env/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/larisayusina/Desktop/environments/selenium_env/lib/python3.9/site-packages/_pytest/fixtures.py\", line 918, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/larisayusina/Desktop/environments/selenium_env/lib/python3.9/site-packages/_pytest/fixtures.py\", line 778, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/larisayusina/Desktop/stepik_lessons/module_5/test_product_page.py\", line 75, in setup\n    self.page.should_be_authorized_user()\n  File \"/Users/larisayusina/Desktop/stepik_lessons/module_5/pages/base_page.py\", line 67, in should_be_authorized_user\n    assert self.is_element_present(*LoginPageLocators.USER_ICON), \"User icon is not presented\"\n"}, "start": 1624565480520, "stop": 1624565498950}], "start": 1624565480520, "stop": 1624565498955}