{"uuid": "89fb9958-42c9-4ccc-813f-a53de2f2a358", "children": ["4f38ecc7-bfcc-4a8d-81ae-950a82043503"], "befores": [{"name": "setup", "status": "failed", "statusDetails": {"message": "AssertionError: User icon is not presented\n", "trace": "  File \"/Users/larisayusina/Desktop/environments/selenium_env/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/larisayusina/Desktop/environments/selenium_env/lib/python3.9/site-packages/_pytest/fixtures.py\", line 918, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/larisayusina/Desktop/environments/selenium_env/lib/python3.9/site-packages/_pytest/fixtures.py\", line 778, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/larisayusina/Desktop/stepik_lessons/module_5/test_product_page.py\", line 75, in setup\n    self.page.should_be_authorized_user()\n  File \"/Users/larisayusina/Desktop/stepik_lessons/module_5/pages/base_page.py\", line 67, in should_be_authorized_user\n    assert self.is_element_present(*LoginPageLocators.USER_ICON), \"User icon is not presented\"\n"}, "start": 1624565460549, "stop": 1624565476980}], "start": 1624565460549, "stop": 1624565476986}